sematic_example(
    name = "bert_fine_tune_scam",
    data = ["data/spam_data.csv"],
    requirements = [
        "torch",
        "torchvision",
        "torchmetrics",
        "plotly",
        "pandas",
        "scikit-learn",
        "transformers",
    ],
)